apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
  - name: file-create
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          echo "Some line" > file.txt;
          sleep 5;
        done
  - name: file-read
    image: busybox
    
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          cat file.txt
          sleep 1;
        done
