apiVersion: v1
kind: Pod
metadata:
  name: sidecar
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}

  containers:
    - name: app-container
      image: shivanisarthi123/examimage
      ports: 
        - containerPort: 3000
      command: ["sh","-c","while true; do date >> /var/log/log.txt; sleep 5;done"]
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log

    - name: sidecar-container
      image: nginx
      ports:
      - containerPort: 80
      volumeMounts:
        - name: shared-logs
          mountPath: /usr/share/nginx/html

